// Hand-maintained catalog metadata: categories, category assignment and per-example
// overrides (platform, German UI note, geometry) that cannot be derived automatically.
// Everything else in fastled-examples.json is generated by build-catalog.mjs.
// After a FastLED pin update: new examples get a category from the path/name rules below
// (fallback 'advanced') and an automatic platform/note; review them and add entries here.

export const SCHEMA_VERSION = 1;

export const CATEGORIES = [
  { id: 'basics', title: 'Basics', titleDe: 'Grundlagen' },
  { id: 'classic', title: 'Classic effects', titleDe: 'Klassische Effekte' },
  { id: 'color', title: 'Color & Palettes', titleDe: 'Farbe & Paletten' },
  { id: 'noise', title: 'Noise', titleDe: 'Noise' },
  { id: 'fire', title: 'Fire', titleDe: 'Feuer' },
  { id: 'matrix', title: 'Matrix / 2D', titleDe: 'Matrix / 2D' },
  { id: 'fx', title: 'FX library', titleDe: 'FX-Bibliothek' },
  { id: 'multi', title: 'Multiple strips', titleDe: 'Mehrere Strips' },
  { id: 'audio', title: 'Audio', titleDe: 'Audio' },
  { id: 'hardware', title: 'Hardware / drivers', titleDe: 'Hardware / Treiber' },
  { id: 'wasm', title: 'WASM / UI', titleDe: 'WASM / UI' },
  { id: 'advanced', title: 'Advanced', titleDe: 'Fortgeschritten' },
];

const BY_ID = {
  basics: ['Blink', 'FirstLight', 'Cylon', 'RGBCalibrate', 'RGBSetDemo', 'PinMode', 'Test', 'WS2816', 'AnalogOutput'],
  classic: ['DemoReel100', 'Pride2015', 'Pacifica', 'TwinkleFox', 'EaseInOut', 'FestivalStick'],
  color: ['ColorPalette', 'ColorTemperature', 'ColorBoost', 'ColorProfile', 'HSVTest', 'RGBW', 'RGBWColorimetric', 'RGBWEmulated', 'RGBWW'],
  noise: ['Noise', 'NoisePlusPalette', 'NoisePlayground', 'FlowField'],
  fire: ['Fire2012', 'Fire2012WithPalette', 'Fire2023', 'FireCylinder', 'FireMatrix'],
  matrix: ['XYMatrix', 'Blur', 'Blur2d', 'Wave', 'Wave2d', 'XYPath', 'Downscale', 'Corkscrew', 'Animartrix', 'AnimartrixRing',
    'Chromancer', 'PerfDisc', 'Luminova'],
  multi: ['ArrayOfLedArrays', 'MirroringSample', 'MultiArrays', 'MultipleStripsInOneArray', 'BlinkParallel'],
  audio: ['Audio', 'AudioFftParity', 'AudioInput', 'AudioReactive', 'AudioUrl', 'BeatDetection', 'ElPanelReactive', 'Sailboat',
    'hydropack', 'MoodRing', 'PJRCSpectrumAnalyzer', 'LuminescentGrand'],
  hardware: ['Apa102', 'Apa102HD', 'HD107', 'Spi', 'ParallelSPI', 'MultipleEsp32SpiBuses', 'ParallelOutputDemo', 'Esp8266Uart', 'OTA',
    'RX', 'Overclock', 'Pintest', 'SmartMatrix'],
  wasm: ['wasm', 'UITest', 'WasmScreenCoords', 'Json'],
  advanced: ['Async', 'AutoResearch', 'Codec', 'Remote', 'SIMD', 'BlurBenchmark'],
};
const CAT_OF = new Map(Object.entries(BY_ID).flatMap(([cat, ids]) => ids.map((id) => [id, cat])));

/** Category of a discovered sketch ({id, name, upstreamPath}). */
export function categorize(ex) {
  if (CAT_OF.has(ex.name)) return CAT_OF.get(ex.name);
  const p = ex.upstreamPath;
  if (p.startsWith('Fx/')) return 'fx';
  if (p.startsWith('SpecialDrivers/') || p.startsWith('Ports/')) return 'hardware';
  if (p.startsWith('Multiple/')) return 'multi';
  if (p.startsWith('Asio/')) return 'advanced';
  if (/audio|beat|fft|sound|mic/i.test(p)) return 'audio';
  if (/fire/i.test(p)) return 'fire';
  if (/noise/i.test(p)) return 'noise';
  if (/color|palette|rgbw|hsv/i.test(p)) return 'color';
  if (/matrix|xy|2d|wave|blur/i.test(p)) return 'matrix';
  if (/wasm|ui/i.test(p)) return 'wasm';
  return 'advanced';
}

// Per-example overrides keyed by catalog id.
//   platform: 'pc' | 'hardware'   (overrides the automatic decision)
//   note:     short German text for the catalog UI
//   geometry: { dim, width, height, shape? }  (overrides the automatic guess)
//   reason:   English one-liner for CATALOG_RESULTS.md (why it fails / is hardware-only)
export const EXAMPLE_META = {
  // --- run on PC, but with a remark
  AnalogOutput: { note: 'Eine analoge RGB-LED (PWM-Pins); im PC-Modus als einzelner Farbpunkt mit Farbwechsel.' },
  Apa102: { note: 'APA102-Strip (SPI-Chipsatz), statisches Bild; L2-Leitungsbytes nur eingeschränkt.' },
  Apa102HD: { note: 'APA102HD-Gamma-Demo (SPI-Chipsatz), statisches Bild; L2-Leitungsbytes nur eingeschränkt.' },
  HD107: { note: 'HD107S-Strip (SPI-Chipsatz), statisches Bild; L2-Leitungsbytes nur eingeschränkt.' },
  EaseInOut: { note: 'Zeigt die Easing-Kurve als statisches Bild auf 100×100; Kurventyp per UI.' },
  XYPath: { note: 'Pfad-Rendering auf 64×64; Bild ändert sich über die UI-Regler.' },
  Wave: { note: 'Läuft im PC-Modus (100 LEDs); Wellen per UI-Button „Trigger“ auslösen.' },
  Overclock: { note: 'Läuft im PC-Modus (22×22); das eigentliche Thema (Übertakten des Treibers) ist Hardware.' },
  TeensyMassiveParallel: { note: 'Teensy-Beispiel im Fallback-Modus: läuft im PC-Modus (60 LEDs).' },
  AdafruitBridge: { note: 'Adafruit-NeoPixel-Bridge; läuft im PC-Modus (10 LEDs).' },
  MoodRing: { note: 'Ring mit 244 LEDs; ohne Mikrofon im Fallback-Modus (ruhige Animation).' },
  Sailboat: { note: 'Läuft im PC-Modus (200 LEDs); ohne Audio-Eingang nur Grundanimation.' },
  LuminescentGrand: { note: 'Klavier-Visualisierung (1.760 LEDs); ohne MIDI-Eingang nur Demo-Animation.' },
  FestivalStick: { note: 'Läuft im PC-Modus (288 LEDs, viele UI-Regler).' },
  Json: { note: 'JSON-API-Demo; läuft im PC-Modus (100 LEDs), Details in der Konsole.' },
  Async: { note: 'Async-Task-Demo; läuft im PC-Modus (60 LEDs).' },
  Noise: { geometry: { dim: 2, width: 16, height: 16, source: 'source' } },
  // --- hardware / not meaningful in PC mode
  Audio: { platform: 'hardware', note: 'Braucht Audio-Eingang (Mikrofon); im PC-Modus ohne Reaktion.', reason: 'audio input (Teensy/ESP32)' },
  AudioReactive: { platform: 'hardware', note: 'Braucht Audio-Eingang (Teensy/ESP32); im PC-Modus dunkel.', reason: 'audio input' },
  AudioUrl: { platform: 'hardware', note: 'Spielt Audio von einer URL ab – kein Netzwerk/Audio im PC-Modus, dunkel.', reason: 'network audio stream' },
  AudioInput: { platform: 'hardware', note: 'I2S-/Teensy-Audio-Eingang; keine LEDs.', reason: 'audio input driver only' },
  AudioFftParity: { platform: 'hardware', note: 'Selbsttest des ESP-DSP-FFT-Backends; keine LEDs.', reason: 'ESP32 DSP self-test' },
  BeatDetection: { platform: 'hardware', note: 'Beat-Erkennung braucht Audio-Eingang; im PC-Modus dunkel.', reason: 'audio input' },
  ElPanelReactive: { platform: 'hardware', note: 'Steuert EL-Panels per PWM (keine LEDs); Visualisierung nur im FastLED-Web-Compiler.', reason: 'EL panels via PWM; LED view only under __EMSCRIPTEN__' },
  hydropack: { platform: 'hardware', note: 'Musikreaktiv (ESP32 + Audio); im PC-Modus dunkel.', reason: 'audio input' },
  PJRCSpectrumAnalyzer: { platform: 'hardware', note: 'Teensy-only (OctoWS2811 + Audio-Bibliothek).', reason: 'needs OctoWS2811.h / Teensy Audio library' },
  Esp8266Uart: { platform: 'hardware', note: 'ESP8266-UART-Treiber; nur für ESP8266.', reason: 'ESP8266-only driver class' },
  OTA: { platform: 'hardware', note: 'Over-the-Air-Update für ESP32 (WLAN); im PC-Modus nur statisches Bild.', reason: 'ESP32 WiFi/OTA' },
  RX: { platform: 'hardware', note: 'ESP32-RX-Kanaltest (Draht zwischen TX und RX nötig); keine LEDs.', reason: 'ESP32 RMT RX test' },
  Spi: { platform: 'hardware', note: 'SPI-Treiber-Demo ohne LED-Controller im PC-Modus.', reason: 'hardware SPI bus' },
  ParallelSPI: { platform: 'hardware', note: 'Paralleler SPI-Bus (Hardware); keine LEDs im PC-Modus.', reason: 'hardware parallel SPI' },
  MultipleEsp32SpiBuses: { platform: 'hardware', note: 'Zwei ESP32-SPI-Busse; keine LEDs im PC-Modus.', reason: 'ESP32 SPI buses' },
  ParallelOutputDemo: { platform: 'hardware', note: 'Teensy-Parallelausgabe; im PC-Modus keine LEDs.', reason: 'Teensy parallel output' },
  Pintest: { platform: 'hardware', note: 'Pin-Test für AVR/Teensy; nur Konsolenausgabe.', reason: 'pin test, console only' },
  PinMode: { platform: 'hardware', note: 'Prüft pinMode/digitalWrite/digitalRead; nur Konsolenausgabe.', reason: 'GPIO test, console only' },
  SmartMatrix: { platform: 'hardware', note: 'SmartMatrix-HUB75-Panel (Teensy); keine LEDs im PC-Modus.', reason: 'SmartMatrix library / Teensy' },
  DriverTest: { platform: 'hardware', note: 'Testet die ESP32-LED-Treiber; im PC-Modus dunkel.', reason: 'ESP32 driver test' },
  Parallel_IO: { platform: 'hardware', note: 'Nur RP2040/RP2350 (Pico).', reason: '#error outside RP2040/RP2350' },
  OctoWS2811: { platform: 'hardware', note: 'Teensy-only (OctoWS2811-Bibliothek).', reason: 'needs OctoWS2811.h' },
  OctoWS2811Demo: { platform: 'hardware', note: 'Teensy-only (OctoWS2811-Bibliothek).', reason: 'needs OctoWS2811.h' },
  RGBCalibrate: { platform: 'hardware', note: 'Alle addLeds()-Zeilen sind im Original auskommentiert – erst einen Chipsatz einkommentieren.', reason: 'all addLeds() commented out upstream' },
  Test: { platform: 'hardware', note: 'Selbsttest der 8-Bit-Mathematik; nur Konsolenausgabe.', reason: 'self-test, console only' },
  SIMD: { platform: 'hardware', note: 'Selbsttest der SIMD-Funktionen; nur Konsolenausgabe.', reason: 'self-test, console only' },
  BlurBenchmark: { platform: 'hardware', note: 'AVR-Benchmark (Gauß-Blur); nur Konsolenausgabe.', reason: 'benchmark, console only' },
  PerfDisc: { platform: 'hardware', note: 'AVR-Benchmark (drawDisc); nur Konsolenausgabe.', reason: 'benchmark, console only' },
  Codec: { platform: 'hardware', note: 'Decodiert JPEG/WebP/GIF/MPEG1 per Button; im PC-Modus bleibt die Matrix dunkel.', reason: 'decoders produce no frame on the stub platform' },
  Remote: { platform: 'hardware', note: 'RPC-Demo über serielle Schnittstelle; ohne Gegenstelle dunkel.', reason: 'needs RPC peer' },
  Client: { platform: 'hardware', note: 'HTTP-Client – kein Netzwerk im PC-Modus; LEDs zeigen nur einen Status.', reason: 'network (sandbox has none)' },
  ClientValidation: { platform: 'hardware', note: 'HTTP-Client-Selbsttest – kein Netzwerk im PC-Modus.', reason: 'network; sketch includes stub_main.hpp (own main()), so no native reference' },
  Loopback: { platform: 'hardware', note: 'HTTP-Server-Loopback-Test – kein Netzwerk im PC-Modus.', reason: 'network' },
  Server: { platform: 'hardware', note: 'HTTP-Server – kein Netzwerk im PC-Modus.', reason: 'network' },
  RpcBidirectional: { platform: 'hardware', note: 'HTTP-Streaming-RPC (Host-Netzwerk + Threads); nicht verfügbar.', reason: 'needs FastLED networking (HttpStreamServer) and std::thread' },
  RpcClient: { platform: 'hardware', note: 'HTTP-Streaming-RPC-Client; nicht verfügbar (kein Netzwerk).', reason: 'needs FastLED networking (HttpStreamClient)' },
  RpcServer: { platform: 'hardware', note: 'HTTP-Streaming-RPC-Server; nicht verfügbar (kein Netzwerk).', reason: 'needs FastLED networking (HttpStreamServer)' },
  AutoResearch: { platform: 'hardware', note: 'FastLED-interne Test-/Benchmark-Suite für Hardware; blockiert im PC-Modus.', reason: 'hardware test harness; no frame within 90 s' },
  FxLedmapper32x32: { platform: 'hardware', note: 'Spielt ein Video aus einer Datei (nicht im Bundle, kein Dateisystem); keine LEDs.', reason: 'video asset / filesystem' },
  FxSdCard: { platform: 'hardware', note: 'Spielt ein Video von SD-Karte; kein Dateisystem im PC-Modus.', reason: 'SD card / filesystem' },
  WasmScreenCoords: { platform: 'hardware', note: 'Nur im FastLED-Web-Compiler (Code steht hinter #ifdef __EMSCRIPTEN__); hier leer.', reason: 'code only under __EMSCRIPTEN__' },
};
